FROM apache/airflow:2.8.0
USER root
RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir \
    requests==2.31.0 \
    beautifulsoup4==4.12.2 \
    kafka-python-ng==2.2.3 \
    minio==7.1.0 \
    psycopg2-binary==2.9.9 \
    langdetect==1.0.9 \
    pandas==1.5.3 \
    python-dotenv==1.0.0 \
    lxml==4.9.3
