apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: newsdb
    user: news_user
    secureJsonData:
      password: news_pass
    jsonData:
      sslmode: disable
    editable: true
